CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA; 

use biblioteca;

CREATE TABLE USUARIOS (
	
	COD INTEGER PRIMARY KEY auto_increment,
    NOMBRE VARCHAR(200) NOT NULL,
    APEL1 VARCHAR(200) NOT NULL,
    APEL2 VARCHAR(200) DEFAULT NULL,
    DIRECCION VARCHAR(200) NOT NULL,
    FNACI DATE NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    TLF VARCHAR (15) UNIQUE,
    FALTA DATETIME NOT NULL, #TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FBAJA DATETIME NOT NULL, 
    OBSERVACIONES MEDIUMTEXT
);

INSERT INTO USUARIOS (NOMBRE, APEL1, APEL2, DIRECCION, FNACI, EMAIL, TLF, FALTA) VALUES 
	('Juan', 'Morote', 'Alcazar', 'Calle del Corazón, 1', '2012-08-16', 'juan@gmail.com', '+34638345565', '2022-06-07'),
	('Fran', 'Barcones','Guerrero','Calle de los Amores, 32', '1976-02-03', 'fran@gmail.com', '+34663123098','2004-04-23'),
	('Margarita', 'Romero', 'Vega', 'Calle de los Ancestros, 64', '1946-09-14', 'abuelamarga@gmail.com', '+34616238432', '1997-11-21');

CREATE TABLE LIBROS (
	
	COD INTEGER PRIMARY KEY auto_increment,
    TITULO VARCHAR(200) NOT NULL COMMENT "PONER TITULO ORIGINAL",
    AUTOR VARCHAR(200) NOT NULL,
    EDITORIAL VARCHAR(200) NOT NULL,
    ISBN VARCHAR(200) NOT NULL,
    GENERO VARCHAR (20) NOT NULL,
    PAGINAS INTEGER NOT NULL,
    FPUBLI DATE,
    FALTA DATETIME NOT NULL, #TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FBAJA DATETIME NOT NULL
);

INSERT INTO LIBROS (TITULO, AUTOR, EDITORIAL, ISBN, GENERO, PAGINAS, FPUBLI, FALTA) VALUES 
	('1984', 'GEORGE ORWELL', 'CONTEMPORANEA', '978-84-9899-094-4', 'CIENCIA FICCION', '350', '1949-12-24', '1975-10-13'),
	('MEDITACIONES', 'MARCO AURELIO', 'TAURUS', '978-84-306-0103-5','FILOSOFIA', '172', '1977-08-30', '1986-02-25'),
	('EL CONTRATO SOCIAL', 'J.J. ROUSSEAU', 'ALMA EDITORIAL', '978-84-18933-23-3', 'TRATADO', '220', '1762-03-04', '1972-07-12'),
	('MOMO', 'MACHAEL ENDE', 'SANTILLANA', '978-84-912-152-4', 'INFANTIL FANTASTICA', '319', '1973-07-17', '2005-01-24');

SELECT * FROM LIBROS;

CREATE TABLE PRESTAMOS (

	COD_PRES INTEGER PRIMARY KEY auto_increment,
	CODUSU INTEGER NOT NULL,
	CODLIB INTEGER NOT NULL,
    CODSAN INTEGER,
    FINICIO DATE NOT NULL, #TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FDEVESPE DATE NOT NULL,
    FDEVREAL DATE NOT NULL,
    NIVEL_SANCION CHAR(15),
    MENSAJE MEDIUMTEXT,
    FOREIGN KEY (CODUSU) REFERENCES USUARIOS(COD)
    	ON DELETE CASCADE
		ON UPDATE CASCADE,
    FOREIGN KEY (CODLIB) REFERENCES LIBROS(COD)
        ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (CODSAN) REFERENCES SANCIONADOS(COD)
        ON DELETE CASCADE
		ON UPDATE CASCADE     
);

INSERT INTO PRESTAMOS (CODUSU, CODLIB, FINICIO, FDEVESPE, FDEVREAL) VALUES
	('1', '4', '2025-02-12','2025-04-12','2025-04-01'),
	('2', '2', '2022-05-06','2022-07-06','2022-08-19'),
	('3', '1', '1998-11-18','1999-01-18','1999-01-03'),
	('2', '3', '2002-03-21','2002-05-21','2002-04-27'),
	('2', '1', '2008-09-30','2008-11-30','2008-10-18'),
	('3', '2', '2004-06-15','2004-08-15','2004-08-25'),
	('1', '2', '2001-01-08','2001-03-08','2001-05-23');

SELECT * FROM PRESTAMOS; 

CREATE TABLE SANCIONADOS(
	COD INTEGER PRIMARY KEY auto_increment,
    CODUSU INT,
    F_PRESTAMO DATE,
    DIAS_SANCION INT,
    MENSAJE MEDIUMTEXT,
	FOREIGN KEY (CODUSU) REFERENCES USUARIOS(COD)
    	ON DELETE CASCADE
		ON UPDATE CASCADE
);

SELECT * FROM SANCIONADOS; 

/*--------------------------------------------------------------------------------------------------------------------------------*/
#PROCEDIMIENTO ALTA_USUARIOS
CREATE DEFINER=`root`@`localhost` PROCEDURE `ALTA_USUARIOS`(NOMBRE VARCHAR(200), APEL1 VARCHAR(200), APEL2 VARCHAR(200),
DIRECCION VARCHAR(200), FNACI DATE, EMAIL VARCHAR(200), TFL CHAR(15), FALTA TIMESTAMP)
BEGIN
		
        INSERT INTO USUARIOS (NOMBRE, APEL1, APEL2, DIRECCION,FNACI,EMAIL,TLF,FALTA) 
        VALUES (NOMBRE, APEL1, APEL2, DIRECCION,FNACI,EMAIL,TLF,FALTA);
        SELECT 'Persona registrada correctamente';
             
 END

#LLAMADA PARA EL PROCEDIMIENTO DAR DE ALTA_USUARIO
CALL ALTA_USUARIOS('Laura', 'Martinez', 'Fernadez', 'Avenida de la Dehesa, 23', '2004-12-19', 'laura@gmail.com', '+34675798465', '2021-4-25');

/*--------------------------------------------------------------------------------------------------------------------------------*/
#PROCEDIMIENTO ALTA_LIBROS
CREATE DEFINER=`root`@`localhost` PROCEDURE `ALTA_LIBROS`(TITULO VARCHAR(200),AUTOR VARCHAR(200),EDITORIAL VARCHAR(200),ISBN VARCHAR(200),
GENERO VARCHAR (20),PAGINAS INTEGER,FPUBLI DATE)
BEGIN

	    INSERT INTO LIBROS (TITULO,AUTOR,EDITORIAL,ISBN,GENERO,PAGINAS,FPUBLI,FALTA) 
        VALUES (TITULO,AUTOR,EDITORIAL,ISBN,GENERO,PAGINAS,FPUBLI,FALTA);
        SELECT 'Libro registrado correctamente';
        
END

#LLAMADA PARA EL PROCEDIMIENTO DAR DE ALTA_LIBRO
CALL ALTA_LIBROS('EL PRINCIPITO', 'ANTOINE DE SAINT-EXUPÉRY', '978-84-9838-149-8','CINECIA FICCIÓN FANTÁSTICA','93','1943-04-23','1971-11-23'); 

/*--------------------------------------------------------------------------------------------------------------------------------*/
#PROCEDIMIENTO ALTA_PRESTAMOS
CREATE DEFINER=`root`@`localhost` PROCEDURE `ALTA_PRESTAMOS`(CODUSU INTEGER, CODLIB INTEGER, FINICIO TIMESTAMP, FDEVESPE DATETIME, FDEVREAL DATETIME)
BEGIN

	    INSERT INTO PRESTAMOS (CODUSU, CODLIB, FINICIO, FDEVESPE, FDEVREAL)
        VALUES (CODUSU, CODLIB, FINICIO, FDEVESPE, FDEVREAL);
        SELECT 'Prestamo registrado correctamente';
        
END

#LLAMADA PARA EL PROCEDIMIENTO DAR DE ALTA_PRESTAMO
CALL ALTA_PRESTAMOS('1','5','2025-03-24','2025-05-24','2025-05-21');

/*--------------------------------------------------------------------------------------------------------------------------------*/
#FUNCION SANCION_USUARIO
CREATE DEFINER=`root`@`localhost` FUNCTION `SANCION_USUARIO`(FDEVESPE DATE, FDEVREAL DATE) RETURNS char(15) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
BEGIN

	declare MENSAJE CHAR(15);
    declare RESULTADO INTEGER;
    
        set RESULTADO = datediff(FDEVREAL,FDEVESPE);
    
    if RESULTADO <= 0 then 
		set MENSAJE = 'ACTIVO';
    elseif RESULTADO BETWEEN 1 AND 7  then 
		set MENSAJE = 'ACTIVO';    
	elseif RESULTADO BETWEEN 8 AND 11 then
		set MENSAJE = 'GRAVE';
	else 
		set MENSAJE = 'MUY GRAVE';
	end if;

RETURN MENSAJE;
END

#LLAMADA PARA FUNCION SANCION_USUARIO
SELECT CODUSU,CODLIB,FDEVESPE,FDEVREAL,DATEDIFF(FDEVREAL, FDEVESPE) AS DIAS_RETRASO,SANCION_USUARIO(FDEVESPE, FDEVREAL) AS SANCION
FROM PRESTAMOS;

/*--------------------------------------------------------------------------------------------------------------------------------*/
#FUNCION MENSAJE_SANCION
CREATE DEFINER=`root`@`localhost` FUNCTION `MENSAJE_SANCION`(NOMBRE VARCHAR(200),APEL1 VARCHAR(200),FINICIO DATE,
    FDEVESPE DATE,FDEVREAL DATE,COD_PRES INT) RETURNS mediumtext CHARSET utf8mb4 COLLATE utf8mb4_general_ci
BEGIN
    DECLARE MENSAJE MEDIUMTEXT;
    DECLARE DIAS_RETRASO INT;
    DECLARE NIVEL_SANCION CHAR(15);

    #Calcular días de retraso
    SET DIAS_RETRASO = DATEDIFF(FDEVREAL, FDEVESPE);

    #Calcular el tipo de sanción llamando a la función anterior
    SET NIVEL_SANCION = SANCION_USUARIO(FDEVESPE, FDEVREAL);

    IF DIAS_RETRASO > 0 THEN
        SET MENSAJE = CONCAT('Estimado usuario ', NOMBRE, ' ', APEL1,', el pasado día ', FINICIO,
            ' realizó un préstamo en nuestra biblioteca con código ', COD_PRES,
            ' y ha superado la fecha de entrega prevista en ', DIAS_RETRASO, 
            ' días,',' por lo que le corresponde una sanción ', NIVEL_SANCION, '.');
 
    END IF;

    RETURN MENSAJE;
END

#LLAMADA PARA FUNCION MENSAJE_SANCION
SELECT MENSAJE_SANCION('Fran','Barcones','2022-05-06','2022-07-06','2022-08-19',2);

/*--------------------------------------------------------------------------------------------------------------------------------*/
#PROCEDIMIENTO GESTOR
CREATE DEFINER=`root`@`localhost` PROCEDURE `GESTOR`()
BEGIN
    DECLARE COD_PRES INT;
    DECLARE CODUSU INT;
    DECLARE FINICIO DATE;
    DECLARE FDEVESPE DATE;
    DECLARE FDEVREAL DATE;
    DECLARE NOMBRE VARCHAR(200);
    DECLARE APEL1 VARCHAR(200);
    DECLARE NIVEL_SANCION CHAR(15);
    DECLARE MENSAJE MEDIUMTEXT;
    DECLARE DIAS INT;
    
    
	#ACTUALIZO LA TABLA PRESTAMOS CON LAS FUNCIONES
    UPDATE PRESTAMOS P JOIN USUARIOS U ON P.CODUSU = U.COD
    SET P.NIVEL_SANCION = SANCION_USUARIO(P.FDEVESPE, P.FDEVREAL),
        P.MENSAJE = MENSAJE_SANCION(U.NOMBRE,U.APEL1,P.FINICIO,P.FDEVESPE,P.FDEVREAL,P.COD_PRES);
	
    #INSERTAMOS EN LA TABLA SANCIONADOS, SOLO SI LA SANCIÓN ES GRAVE O MUY GRAVE
	INSERT INTO SANCIONADOS (CODUSU, F_PRESTAMO, DIAS_SANCION, MENSAJE) 
    SELECT P.CODUSU,P.FINICIO,DATEDIFF(P.FDEVREAL, P.FDEVESPE),P.MENSAJE FROM PRESTAMOS P
	WHERE P.NIVEL_SANCION IN ('GRAVE', 'MUY GRAVE');
    
    #ACTUALIZO LA COLUMNA CODSAN en PRESTAMOS con la clave de SANCIONADOS
    UPDATE PRESTAMOS P
    JOIN SANCIONADOS S ON P.CODUSU = S.CODUSU AND P.FINICIO = S.F_PRESTAMO
    SET P.CODSAN = S.COD;
    
END

#DESACTIVO EL MODO SEGURO PARA EJECUTAR EL PROCEDIMIENTO GESTOR
SET SQL_SAFE_UPDATES = 0;

CALL GESTOR();

#ACTIVO EL MODO SEGURO
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM PRESTAMOS;
SELECT * FROM SANCIONADOS;


